### ISSUE TITLE
Crazy lag-spike every time entering a new zone.

### ISSUE THREAD

**Issue by Megaddd** [viktorgullmark/exile-party#14]
exile-party creates a huge network lag-spike by utilizing 100% of the network for 3-4 seconds on entering a zone every time, making Path of Exile unplayable for 4 seconds at the start of the zone.

As you mentioned in #9, there is no good reason for this as you only update the net wealth every 7.5 minutes.

The network usage type from exile-party during these zone changes is a huge upload followed by a large download.

**Comment by petterannerwall** [comment]
This is probably due to the size of the player object with saved income/network graph combined with the areas array, How many stashtabs have you selected in the settings and how many snapshots are there in the graph? And how many areas is listed under the area tab?

This is a problem not only for you but for us aswell, since every zone  change the player object gets sent to the server and then broadcasted to everyone else in the group and bandwidth costs money. 

The good news is that we are working on a fix in the /features/compression branch where we compress the messages before sending them to the server.

**Comment by Megaddd** [comment]
I have a somewhat capable 30-40Mbit connection, and I'm serious when I say these character sync. might cause a rip in a Hardcore league
Exhibit A - https://gfycat.com/FortunatePolishedBlackwidowspider
Exhibit B - https://gfycat.com/HauntingPlasticArmyant
Exhibit C - https://gfycat.com/CompleteFriendlyIsopod

**Comment by Megaddd** [comment]
Perhaps cache the player objects in RAM both locally and server-side, and only communicate the changes in them?

**Comment by petterannerwall** [comment]
Thanks for the gif's will come in handy! 

Did you have any information about how many stashtabs were selected under settings and how many snapshots were in the graph along with areas visited?

**Comment by Megaddd** [comment]
Can you simply join 'No Doctors Allowed' to see what I see?

**Comment by viktorgullmark** [comment]
Compression has been added in 0.4.4. We've reduced the network used by 2/3. Closing this.
